### ISSUE TITLE
Error opening bookmarks

### ISSUE THREAD

**Issue by amaterasu** [sysid/bkmr#20]
What i am trying to do

`bkmr open 1 # or any other id `

Error

```
thread 'main' panicked at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bkmr-2.0.0/src/main.rs:423:30:
called `Result::unwrap()` on an `Err` value: (bkmr::service::process::_open_bm::{{closure}}:393) Error OS opening https://www.google.com

Caused by:
    Launcher "gio" "open" "https://www.google.com" failed with ExitStatus(unix_wait_status(512))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Additional Info:

I am using bkmr with Windows 11 wsl  (Ubuntu)

**Comment by sysid** [comment]
@amaterasu , thanks for taking time to report this issue. 

Unfortunately I do neither use WSL nor  "gio", so I cannot say anything to this issue. "xdg-open" and macos "open" are supposed to work as OS launcher. Actually, `bkmr` does just use the default OS launcher to open the URL. 

PR is very welcome, of course in case you have any interest. 

But since I unfortunately am lacking the means to work on this issue I am going to close it an unresolved for now.
